version: "1"

services:
  web:
    build: 
      context: .
      dockerfile: ./backend/database/flask_dockerfile
    ports:
      - "9001:5000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 2G  # Set the memory limit for the 'web' service to 2GB
  dashboard:
    build: 
      context: .
      dockerfile: ./backend/dashboard/app/dashboard_dockerfile
    ports:
      - "3838:3838"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./backend/database/database_dockerfile
    ports:
      - "3307:3306"
  
    
